ERROR - 2025-03-29 13:40:50 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci_post2Approve', 3306, '', 0)
#1 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\ci_2Approval\app\Controllers\AuthController.php(77): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->login()
#8 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#9 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\laragon\www\ci_2Approval\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#5 C:\laragon\www\ci_2Approval\app\Controllers\AuthController.php(77): CodeIgniter\BaseModel->first()
#6 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->login()
#7 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\laragon\www\ci_2Approval\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#13 {main}
CRITICAL - 2025-03-29 13:40:50 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\AuthController.php(77): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->login()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
CRITICAL - 2025-03-29 15:38:35 --> ErrorException: Undefined variable $selectedApproverId
[Method: GET, Route: admin/posts/tutorial-codeigniter-4-untuk-pemula]
in APPPATH\Views\admin\post.php on line 30.
 1 APPPATH\Views\admin\post.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $selectedApproverId', 'C:\\laragon\\www\\ci_2Approval\\app\\Views\\admin\\post.php', 30)
 2 SYSTEMPATH\View\View.php(224): include('C:\\laragon\\www\\ci_2Approval\\app\\Views\\admin\\post.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->{closure:CodeIgniter\View\View::render():221}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('admin/post', [], true)
 5 APPPATH\Controllers\admin\PostsController.php(51): view('admin/post', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\admin\PostsController->detail('tutorial-codeigniter-4-untuk-pemula')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
ERROR - 2025-03-29 15:46:52 --> mysqli_sql_exception: Unknown column 'uid_approve_1' in 'field list' in C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `uid_app...', 0)
#1 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `uid_app...')
#2 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `uid_app...')
#3 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `uid_app...', Array, false)
#4 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\ci_2Approval\app\Controllers\admin\PostsController.php(43): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\admin\PostsController->detail('tutorial-codeig...')
#8 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
#9 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\laragon\www\ci_2Approval\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#14 {main}
CRITICAL - 2025-03-29 15:46:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'uid_approve_1' in 'field list'
[Method: GET, Route: admin/posts/tutorial-codeigniter-4-untuk-pemula]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = :slug:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\admin\PostsController.php(43): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\admin\PostsController->detail('tutorial-codeigniter-4-untuk-pemula')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
CRITICAL - 2025-03-29 15:46:52 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'uid_approve_1' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = \'tutorial-codeigniter-4-untuk-pemula\'
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = \'tutorial-codeigniter-4-untuk-pemula\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = :slug:
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 6 APPPATH\Controllers\admin\PostsController.php(43): CodeIgniter\BaseModel->first()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\admin\PostsController->detail('tutorial-codeigniter-4-untuk-pemula')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
CRITICAL - 2025-03-29 15:46:52 --> [Caused by] mysqli_sql_exception: Unknown column 'uid_approve_1' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = \'tutorial-codeigniter-4-untuk-pemula\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = \'tutorial-codeigniter-4-untuk-pemula\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = \'tutorial-codeigniter-4-untuk-pemula\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = :slug:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 7 APPPATH\Controllers\admin\PostsController.php(43): CodeIgniter\BaseModel->first()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\admin\PostsController->detail('tutorial-codeigniter-4-untuk-pemula')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
ERROR - 2025-03-29 15:47:06 --> mysqli_sql_exception: Unknown column 'uid_approve_1' in 'field list' in C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `uid_app...', 0)
#1 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `uid_app...')
#2 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `uid_app...')
#3 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `uid_app...', Array, false)
#4 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\ci_2Approval\app\Controllers\admin\PostsController.php(43): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\admin\PostsController->detail('tutorial-codeig...')
#8 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
#9 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\laragon\www\ci_2Approval\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#14 {main}
CRITICAL - 2025-03-29 15:47:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'uid_approve_1' in 'field list'
[Method: GET, Route: admin/posts/tutorial-codeigniter-4-untuk-pemula]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = :slug:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\admin\PostsController.php(43): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\admin\PostsController->detail('tutorial-codeigniter-4-untuk-pemula')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
CRITICAL - 2025-03-29 15:47:06 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'uid_approve_1' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = \'tutorial-codeigniter-4-untuk-pemula\'
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = \'tutorial-codeigniter-4-untuk-pemula\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = :slug:
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 6 APPPATH\Controllers\admin\PostsController.php(43): CodeIgniter\BaseModel->first()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\admin\PostsController->detail('tutorial-codeigniter-4-untuk-pemula')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
CRITICAL - 2025-03-29 15:47:06 --> [Caused by] mysqli_sql_exception: Unknown column 'uid_approve_1' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = \'tutorial-codeigniter-4-untuk-pemula\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = \'tutorial-codeigniter-4-untuk-pemula\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = \'tutorial-codeigniter-4-untuk-pemula\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = :slug:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 7 APPPATH\Controllers\admin\PostsController.php(43): CodeIgniter\BaseModel->first()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\admin\PostsController->detail('tutorial-codeigniter-4-untuk-pemula')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
ERROR - 2025-03-29 15:47:08 --> mysqli_sql_exception: Unknown column 'uid_approve_1' in 'field list' in C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `uid_app...', 0)
#1 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `uid_app...')
#2 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `uid_app...')
#3 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `uid_app...', Array, false)
#4 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\ci_2Approval\app\Controllers\admin\PostsController.php(43): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\admin\PostsController->detail('tutorial-codeig...')
#8 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
#9 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\laragon\www\ci_2Approval\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\laragon\www\ci_2Approval\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#14 {main}
CRITICAL - 2025-03-29 15:47:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'uid_approve_1' in 'field list'
[Method: GET, Route: admin/posts/tutorial-codeigniter-4-untuk-pemula]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = :slug:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\admin\PostsController.php(43): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\admin\PostsController->detail('tutorial-codeigniter-4-untuk-pemula')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
CRITICAL - 2025-03-29 15:47:08 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'uid_approve_1' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = \'tutorial-codeigniter-4-untuk-pemula\'
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = \'tutorial-codeigniter-4-untuk-pemula\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = :slug:
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 6 APPPATH\Controllers\admin\PostsController.php(43): CodeIgniter\BaseModel->first()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\admin\PostsController->detail('tutorial-codeigniter-4-untuk-pemula')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
CRITICAL - 2025-03-29 15:47:08 --> [Caused by] mysqli_sql_exception: Unknown column 'uid_approve_1' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = \'tutorial-codeigniter-4-untuk-pemula\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = \'tutorial-codeigniter-4-untuk-pemula\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = \'tutorial-codeigniter-4-untuk-pemula\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `uid_approve_1`
FROM `posts`
WHERE `slug` = :slug:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 7 APPPATH\Controllers\admin\PostsController.php(43): CodeIgniter\BaseModel->first()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\admin\PostsController->detail('tutorial-codeigniter-4-untuk-pemula')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
CRITICAL - 2025-03-29 15:50:31 --> ErrorException: Undefined variable $ap1
[Method: GET, Route: admin/posts/tutorial-codeigniter-4-untuk-pemula]
in APPPATH\Views\admin\post.php on line 29.
 1 APPPATH\Views\admin\post.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $ap1', 'C:\\laragon\\www\\ci_2Approval\\app\\Views\\admin\\post.php', 29)
 2 SYSTEMPATH\View\View.php(224): include('C:\\laragon\\www\\ci_2Approval\\app\\Views\\admin\\post.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->{closure:CodeIgniter\View\View::render():221}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('admin/post', [], true)
 5 APPPATH\Controllers\admin\PostsController.php(54): view('admin/post', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\admin\PostsController->detail('tutorial-codeigniter-4-untuk-pemula')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
CRITICAL - 2025-03-29 17:09:27 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: admin/updateApprover/1]
in SYSTEMPATH\BaseModel.php on line 1010.
 1 SYSTEMPATH\BaseModel.php(1010): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\admin\PostsController.php(63): CodeIgniter\Model->update('1', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\admin\PostsController->updateApprover('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
CRITICAL - 2025-03-29 17:12:37 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: admin/updateApprover/1]
in SYSTEMPATH\BaseModel.php on line 1010.
 1 SYSTEMPATH\BaseModel.php(1010): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\admin\PostsController.php(64): CodeIgniter\Model->update('1', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\admin\PostsController->updateApprover('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
CRITICAL - 2025-03-29 17:15:15 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: admin/updateApprover/1]
in SYSTEMPATH\BaseModel.php on line 1010.
 1 SYSTEMPATH\BaseModel.php(1010): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\admin\PostsController.php(65): CodeIgniter\Model->update('1', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\admin\PostsController->updateApprover('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
CRITICAL - 2025-03-29 17:23:13 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: admin/updateApprover/1]
in SYSTEMPATH\BaseModel.php on line 1010.
 1 SYSTEMPATH\BaseModel.php(1010): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\admin\PostsController.php(70): CodeIgniter\Model->update('1', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\admin\PostsController->updateApprover('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
CRITICAL - 2025-03-29 17:28:29 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: admin/updateApprover/1]
in SYSTEMPATH\BaseModel.php on line 1010.
 1 SYSTEMPATH\BaseModel.php(1010): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\admin\PostsController.php(71): CodeIgniter\Model->update(1, [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\admin\PostsController->updateApprover(1)
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
CRITICAL - 2025-03-29 17:29:13 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: admin/updateApprover/1]
in SYSTEMPATH\BaseModel.php on line 1010.
 1 SYSTEMPATH\BaseModel.php(1010): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\admin\PostsController.php(74): CodeIgniter\Model->update(1, [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\admin\PostsController->updateApprover(1)
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\PostsController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\ci_2Approval\\public\\index.php')
